const express = require('express');

const activityRoutes = require('./modules/activity/activity-routes');
const userRoutes = require('./modules/user/user-routes');
const authRoutes = require('./modules/auth/auth-routes');
const businessRoutes = require('./modules/business/business-routes');
const askRoutes = require('./modules/aiChat/ai-chat-routes');
const chatRoutes = require('./modules/chat/chat-routes');
const knowledgeRoutes = require('./modules/knowledge/knowledge-routes');
const escalationRoutes = require('./modules/escalation/escalation-routes');
const sessionRoutes = require('./modules/session/session-routes');
const notesRoutes = require('./modules/notes/notes-routes');
const emailRoutes = require('./modules/email/email-routes');
const categoryRoutes = require('./modules/category/category-routes');
const faqRoutes = require('./modules/faq/faq-routes');
const policyRoutes = require('./modules/policy/policy-routes');
const serviceRoutes = require('./modules/service/service-routes');
const productRoutes = require('./modules/product/product-routes');
const agentRoutes = require('./modules/agent/agent-routes');  
const agentRatingRoutes = require('./modules/agent-rating/agent-rating-route');
const analyticsRoutes = require('./modules/analytics/analytics-routes');
const queueRoutes = require('./modules/queue/queue-routes');
const fileRoutes = require('./modules/file/file-routes');
const chatbotSettingsRoutes = require('./modules/chatbot-settings/chatbot-settings-routes');
const qrSettingsRoutes = require('./modules/qr-settings/qr-settings-routes');

const api = express.Router();

api.use('/auth', authRoutes);
api.use('/user', userRoutes);
api.use('/business', businessRoutes);
api.use('/activity', activityRoutes);
api.use('/ask', askRoutes);
api.use('/chat', chatRoutes);
api.use('/knowledge', knowledgeRoutes);
api.use('/escalation', escalationRoutes);
api.use('/session', sessionRoutes);
api.use('/notes', notesRoutes);
api.use('/email', emailRoutes);
api.use('/category', categoryRoutes);
api.use('/faq', faqRoutes);
api.use('/policy', policyRoutes);
api.use('/service', serviceRoutes);
api.use('/product', productRoutes);
api.use('/agent', agentRoutes);  
api.use('/agent-rating', agentRatingRoutes);
api.use('/analytics', analyticsRoutes);
api.use('/queue', queueRoutes);  
api.use('/file', fileRoutes);  
api.use('/chatbot-settings', chatbotSettingsRoutes);  
api.use('/qr-settings', qrSettingsRoutes);  

module.exports = api;
